### ISSUE TITLE
Always getting error "easyconfig failed".

### ISSUE THREAD

**Issue by arasu01** [torinnguyen/broadlink-ios#1]
I have downloaded your library and installed it in device and launched the app.
Then click on the config bar button and navigated easy config view.
Then I have entered the SSID and password and then click the easy config button.
Then after some seconds received the error "easyconfig failed".

Attached logs for it.
1. Network Init : 
{
    code = 0;
    msg = "Network init success";
}
2016-08-05 18:22:48.704 BroadLinkSDKDemo[1073:224966] Init success!
1. Probe list :
   {"command":"probe_list","api_id":11}
   {
   code = 0;
   list =     (
   );
   msg = "Execute success";
   }
2. Easy Config :
   {
     code = 1;
     msg = "easyconfig failed";
   }

Please let me know what wrong in it.

**Comment by torinnguyen** [comment]
This is a leaked Broadlink SDK that I somehow managed to obtain. I cannot provide support for it. Please contact Broadlink & good luck on that.
